/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuildCakeRouteImport } from './routes/build-cake'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UnauthenticatedOrderConfirmationRouteImport } from './routes/_unauthenticated/order-confirmation'
import { Route as UnauthenticatedComingSoonRouteImport } from './routes/_unauthenticated/comingSoon'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminProductsRouteImport } from './routes/_admin/products'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminHomeRouteImport } from './routes/_admin/home'
import { Route as AdminCustomersRouteImport } from './routes/_admin/customers'
import { Route as AdminCategoriesRouteImport } from './routes/_admin/categories'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCakeRoute = BuildCakeRouteImport.update({
  id: '/build-cake',
  path: '/build-cake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const UnauthenticatedOrderConfirmationRoute =
  UnauthenticatedOrderConfirmationRouteImport.update({
    id: '/order-confirmation',
    path: '/order-confirmation',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedComingSoonRoute =
  UnauthenticatedComingSoonRouteImport.update({
    id: '/comingSoon',
    path: '/comingSoon',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/build-cake': typeof BuildCakeRoute
  '/checkout': typeof CheckoutRoute
  '/feedback': typeof FeedbackRoute
  '/landing': typeof LandingRoute
  '/shop': typeof ShopRoute
  '/categories': typeof AdminCategoriesRoute
  '/customers': typeof AdminCustomersRoute
  '/home': typeof AdminHomeRoute
  '/orders': typeof AdminOrdersRoute
  '/products': typeof AdminProductsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/comingSoon': typeof UnauthenticatedComingSoonRoute
  '/order-confirmation': typeof UnauthenticatedOrderConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/build-cake': typeof BuildCakeRoute
  '/checkout': typeof CheckoutRoute
  '/feedback': typeof FeedbackRoute
  '/landing': typeof LandingRoute
  '/shop': typeof ShopRoute
  '/categories': typeof AdminCategoriesRoute
  '/customers': typeof AdminCustomersRoute
  '/home': typeof AdminHomeRoute
  '/orders': typeof AdminOrdersRoute
  '/products': typeof AdminProductsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/comingSoon': typeof UnauthenticatedComingSoonRoute
  '/order-confirmation': typeof UnauthenticatedOrderConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/build-cake': typeof BuildCakeRoute
  '/checkout': typeof CheckoutRoute
  '/feedback': typeof FeedbackRoute
  '/landing': typeof LandingRoute
  '/shop': typeof ShopRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/home': typeof AdminHomeRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_unauthenticated/comingSoon': typeof UnauthenticatedComingSoonRoute
  '/_unauthenticated/order-confirmation': typeof UnauthenticatedOrderConfirmationRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/build-cake'
    | '/checkout'
    | '/feedback'
    | '/landing'
    | '/shop'
    | '/categories'
    | '/customers'
    | '/home'
    | '/orders'
    | '/products'
    | '/dashboard'
    | '/comingSoon'
    | '/order-confirmation'
    | '/auth/login'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/build-cake'
    | '/checkout'
    | '/feedback'
    | '/landing'
    | '/shop'
    | '/categories'
    | '/customers'
    | '/home'
    | '/orders'
    | '/products'
    | '/dashboard'
    | '/comingSoon'
    | '/order-confirmation'
    | '/auth/login'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/about'
    | '/auth'
    | '/build-cake'
    | '/checkout'
    | '/feedback'
    | '/landing'
    | '/shop'
    | '/_admin/categories'
    | '/_admin/customers'
    | '/_admin/home'
    | '/_admin/orders'
    | '/_admin/products'
    | '/_authenticated/dashboard'
    | '/_unauthenticated/comingSoon'
    | '/_unauthenticated/order-confirmation'
    | '/auth/login'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BuildCakeRoute: typeof BuildCakeRoute
  CheckoutRoute: typeof CheckoutRoute
  FeedbackRoute: typeof FeedbackRoute
  LandingRoute: typeof LandingRoute
  ShopRoute: typeof ShopRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-cake': {
      id: '/build-cake'
      path: '/build-cake'
      fullPath: '/build-cake'
      preLoaderRoute: typeof BuildCakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_unauthenticated/order-confirmation': {
      id: '/_unauthenticated/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof UnauthenticatedOrderConfirmationRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/comingSoon': {
      id: '/_unauthenticated/comingSoon'
      path: '/comingSoon'
      fullPath: '/comingSoon'
      preLoaderRoute: typeof UnauthenticatedComingSoonRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/home': {
      id: '/_admin/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedComingSoonRoute: typeof UnauthenticatedComingSoonRoute
  UnauthenticatedOrderConfirmationRoute: typeof UnauthenticatedOrderConfirmationRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedComingSoonRoute: UnauthenticatedComingSoonRoute,
  UnauthenticatedOrderConfirmationRoute: UnauthenticatedOrderConfirmationRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BuildCakeRoute: BuildCakeRoute,
  CheckoutRoute: CheckoutRoute,
  FeedbackRoute: FeedbackRoute,
  LandingRoute: LandingRoute,
  ShopRoute: ShopRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
